sudo: required
services:
  - docker

before_install:
  - docker build -t thanhma/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true thanhma/react-test npm test --coverage

after_success:
  - docker build -t thanhma791/multi-client ./client
  - docker build -t thanhma791/multi-nginx ./nginx
  - docker build -t thanhma791/multi-server ./server
  - docker build -t thanhma791/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thanhma791/multi-client
  - docker push thanhma791/multi-nginx
  - docker push thanhma791/multi-server
  - docker push thanhma791/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-767398048409"
  bucket_path: "docker-multi"
  on:
    repo: thanhm963/multi-docker
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: "$AWS_SECRET_KEY"
